### ISSUE TITLE
[Feat] 로그인 / 회원 가입 로직 수정

### ISSUE THREAD

**Issue by woogisea** [TeamZOOC/ZOOC-STORE#304]
## 🛠 Issue

- 로그인 / 회원 가입 로직 수정

## 📋 To-do

- [x] 소셜 토큰으로 유저 조회 API 연동
- [x] 회원가입 선택 항목 API 조회 연동
- [x] 유저 분류 후 로그인 / 회원가입 분기처리 및 API 연동
