### ISSUE TITLE
[QA] 1차 QA

### ISSUE THREAD

**Issue by woogisea** [TeamZOOC/ZOOC-STORE#353]
## 🛠 Issue

- 1차 QA

## 📋 To-do

- [x] 간편커스텀, 셀프커스텀 부분 간격 확인
- [x] 웹뷰에서 간편커스텀,셀프 커스텀 스타일 적용 안됨
- [x] 장바구니 접속 시 장바구니 상품이 있어도 empty뷰가 먼저 보였다가 사라짐
