### ISSUE TITLE
[QA] 2차 QA

### ISSUE THREAD

**Issue by woogisea** [TeamZOOC/ZOOC-STORE#355]
## 🛠 Issue

- 2차 QA

## 📋 To-do

- [x] 셀프커스텀 들어가자마자 ‘내 커스텀 AI 캐릭터’ 옆에 에러 아이콘이 떠있는 상황 (디폴트로 떠있는 것이 아님)
- [x] (반려동물 미등록 유저) 셀프커스텀 특정 제품을 누르면 토스트 메세지가 다르게 뜸. + 에러 아이콘이 뜨지 않음.
- [x] 내 커스텀 AI 캐릭터에서 가로스크롤 끝까지 되었을 때 마진값이 디자인에 비해 좁음
