### ISSUE TITLE
[QA] 3차 QA

### ISSUE THREAD

**Issue by woogisea** [TeamZOOC/ZOOC-STORE#360]
## 🛠 Issue

- (반려동물 미등록 유저) 셀프커스텀 특정 제품을 누르면 토스트 메세지가 다르게 뜸. + 에러 아이콘이 뜨지 않음.

## 📋 To-do

- [x] 레이아웃 쉬프트 현상 해결
- [x] character api가 호출안된경우 토스트 메세지 수정
- [x] Next/Image의 deviceSize 조절
